### ISSUE TITLE
fix: cannot run on iOS

### ISSUE THREAD

**Issue by jtkeyva** [alnitak/shader_presets#1]
**Description**
I can see the sliders but no content and i cannot move the sliders: aka it's frozen

Cannot run on iOS and getting this error:

 io.worker.2 signal SIGABRT

/shell/platform/darwin/graphics/FlutterDarwinContextMetalImpeller.mm(42)] Using the Impeller rendering backend.
flutter: The Dart VM service is listening on http://127.0.0.1:64348/jrJgNhfrB8k=/
flutter: LayerBuffer.init() loaded: true  packages/shader_presets/assets/shaders/gl_transitions/cube.frag
-[MTLDebugRenderCommandEncoder validateCommonDrawErrors:]:5775: failed assertion `Draw Errors Validation
Fragment Function(cube_fragment_main): missing buffer binding at index 4 for progress[0].

another attempt gave me this:

[ERROR:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalImpeller.mm(42)] Using the Impeller rendering backend.
fopen failed for data file: errno = 2 (No such file or directory)
Errors found! Invalidating cache...
flutter: The Dart VM service is listening on http://127.0.0.1:62912/SI3sHPyBoHI=/
flutter: LayerBuffer.init() loaded: true  packages/shader_presets/assets/shaders/gl_transitions/cube.frag
fopen failed for data file: errno = 2 (No such file or directory)
Errors found! Invalidating cache...
-[MTLDebugRenderCommandEncoder validateCommonDrawErrors:]:5775: failed assertion `Draw Errors Validation
Fragment Function(cube_fragment_main): missing buffer binding at index 4 for progress[0].
Fragment Function(cube_fragment_main): missing buffer binding at index 5 for persp[0].
'

**Steps To Reproduce**

Run on iOS using XCode

**Expected Behavior**

To run as it does on web

**Screenshots**

**Additional Context**

**Comment by alnitak** [comment]
Hi @jtkeyva 

I think impeller is not yet ready for shaders. Can you please try running the example with impeller disabled?
`flutter run --no-enable-impeller`

**Comment by jtkeyva** [comment]
@alnitak you are correct, it's working. really awesome stuff!

widgets look slightly pixely/grainy. wonder if impeller will fix that?

**Comment by alnitak** [comment]
I think it will be fixed for sure, but don't really know how much it will take

**Comment by jtkeyva** [comment]
how can we notify them?

**Comment by alnitak** [comment]
I wrote the problem in the README.md
